### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by wu-yu-xuan** [hamono/bilibili_text#53]
https://github.com/hamono/bilibili_text/blob/222a90e7f21249728671678b498f03713bd28042/src/views/App.tsx#L45

为什么要包一层？直接`<Route path="..."><PlayPage /></Route>`不行吗？
还有整理一下目录，hook可以专门建个hook文件夹存放，通用组件建个专门的components文件夹存放
另外注意一下格式，不喜欢手动格式化可以打开vscode的fix on save或者哈士奇（in package.json）:
```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
    }
  },
```

**Comment by syntou** [comment]
后面会进行整改

**Comment by syntou** [comment]
好的，我们后面会进行整改
